Repository coopdevs/timeoverflow, pull requests merged in 2019-03, with the labels that each got.

#473 Add Gallego language to TimeOverflow
  config/application.rb
  config/locales/gl.yml
Labels: needs review, needs testing

#466 add branded organization logo
  app/assets/images/redeira.png
  app/helpers/brand_logo_helper.rb
  app/views/application/_brand_logo.html.erb
  app/views/layouts/application.html.erb
  config/initializers/branded_organization.rb
  spec/features/brand_logo_spec.rb
  spec/features/create_offer_spec.rb
Labels: needs review

#481 Feature/group offers
  app/assets/stylesheets/application.css.scss
  app/controllers/posts_controller.rb
  app/views/shared/_post.html.erb
  app/views/shared/_post_form.html.erb
  app/views/shared/_posts.html.erb
  config/locales/en.yml
  db/migrate/20190319121401_add_is_group_to_post.rb
  db/schema.rb
  spec/views/inquiries/show.html.erb_spec.rb
  spec/views/offers/show.html.erb_spec.rb
Labels: needs testing, needs translations
