Repository coopdevs/timeoverflow, pull requests merged in 2021-03, with the labels that each got.

#594 Reports: more internal refactor and include new attributes
  Gemfile.lock
  app/assets/javascripts/application.js
  app/decorators/member_report_decorator.rb
  app/decorators/post_report_decorator.rb
  app/services/report/csv.rb
  app/services/report/csv/base.rb
  app/services/report/csv/member.rb
  app/services/report/csv/post.rb
  app/services/report/pdf.rb
  app/services/report/pdf/base.rb
  app/services/report/pdf/member.rb
  app/services/report/pdf/post.rb
  app/views/reports/post_list.html.erb
  app/views/reports/user_list.html.erb
  spec/controllers/reports_controller_spec.rb
  spec/decorators/member_report_decorator_spec.rb
  spec/decorators/post_report_decorator_spec.rb
Labels: enhancement

#597 Redirect to previous page
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/helpers/application_helper.rb
  spec/controllers/sessions_controller_spec.rb
Labels: feature

#600 Statistics code clean up
  .rubocop.yml
  app/admin/dashboard.rb
  app/controllers/statistics_controller.rb
  app/views/application/menus/_organization_statistics_menu.html.erb
  app/views/statistics/all_transfers.html.erb
  app/views/statistics/demographics.html.erb
  app/views/statistics/global_activity.html.erb
  app/views/statistics/inactive_users.html.erb
  app/views/statistics/last_login.html.erb
  app/views/statistics/type_swaps.html.erb
  app/views/statistics/without_offers.html.erb
  config/locales/ca.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/eu.yml
  config/locales/gl.yml
  config/locales/pt-BR.yml
  config/routes.rb
  spec/controllers/statistics_controller_spec.rb
Labels: needs testing, refactor

#599 Add Transfers Report
  app/controllers/reports_controller.rb
  app/controllers/statistics_controller.rb
  app/decorators/member_decorator.rb
  app/decorators/report/member_decorator.rb
  app/decorators/report/post_decorator.rb
  app/decorators/report/transfer_decorator.rb
  app/helpers/application_helper.rb
  app/helpers/transfers_helper.rb
  app/models/organization.rb
  app/services/report/csv/member.rb
  app/services/report/csv/post.rb
  app/services/report/csv/transfer.rb
  app/services/report/pdf/member.rb
  app/services/report/pdf/post.rb
  app/services/report/pdf/transfer.rb
  app/views/application/_navbar.html.erb
  app/views/application/menus/_organization_reports_menu.html.erb
  app/views/organizations/show.html.erb
  app/views/reports/transfer_list.html.erb
  app/views/statistics/all_transfers.html.erb
  app/views/statistics/type_swaps.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  spec/controllers/reports_controller_spec.rb
  spec/decorators/report/member_decorator_spec.rb
  spec/decorators/report/post_decorator_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/helpers/transfers_helper_spec.rb
Labels: needs testing

#608 Do not allow login to inactive members -- solved
  app/controllers/application_controller.rb
  app/controllers/organizations_controller.rb
  app/controllers/tags_controller.rb
  app/controllers/users_controller.rb
  app/views/organizations/select_organization.html.erb
  app/views/shared/_post.html.erb
  app/views/users/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/organizations_controller_spec.rb
  spec/controllers/tags_controller_spec.rb
  spec/controllers/users_controller_spec.rb
Labels: needs testing
